name: "Bug Report"
description: "Report a bug"
title: "Bug: (the bug you found)"
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: "Thanks for your completing this bug report form. "
- type: textarea
  id: happen
  attributes:
    description: "How does this bug happened? "
    label: happen
    value: |
      1. 
      2. 
  validations: 
    required: true
- type: dropdown
  id: platform
  description: "What is the platform you are using? "
  attributes:
    label: platform
    options:
    - Windows
    - macOS
    - Linux
    - Other
    multiple: true
  validations:
    required: true
- type: textarea
  id: log
  attributes:
    description: "Please paste your logs here. To find the logs, please click the menu. "
    label: log
