name: Bug Report
description: Report a bug
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. 
  - type: textarea
    id: happen
    description: "How does this bug happens? "
    value: |
      1. 
      2. 
    validations: 
      required: true
  - type: textarea
    id: log
    description: "Please paste your logs here. To find the logs, please click the menu. "
 
